spring:
  config:
    import: "configserver:http://localhost:8081"

  application:
    name: reservas-service

  cloud:
    config:
      uri: http://localhost:8081
      label: main

    netflix:
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka
  datasource:
    url: jdbc:mysql://localhost:3306/reservasdb
    username: root
    password: Ignacito1.
  jpa:
    hibernate:
          ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ignacio23012002@gmail.com
    password: tjrh eyro mcrg eedz
    from: ignacio23012002@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          ssl.trust: smtp.gmail.com

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info