server:
  port: 0
spring:
  application:
    name: reportes-service
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reportesdb
    username: tu_usuario
    password: tu_clave
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka