server:
  port: 0

spring:
  application:
    name: reservas-service

  datasource:
    url: jdbc:mysql://localhost:3306/reservasdb
    username: root
    password: Ignacito1.
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
