apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-service
  namespace: karting
  labels:
    app: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-service
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-service
          image: eureka-service:latest
          imagePullPolicy: Never
          env:
            # Fuerza a Spring Boot a escuchar en 8761
            - name: SERVER_PORT
              value: "8761"
          ports:
            - name: http
              containerPort: 8761
