apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: karting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: karting-front:latest
        ports:
        - containerPort: 80
