apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-deploy
  namespace: karting
  labels:
    app: reservas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-service
  template:
    metadata:
      labels:
        app: reservas-service
    spec:
      containers:
        - name: reservas-service
          image: reservas-service:latest
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
