apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  namespace: karting      
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: config-service:latest         
          imagePullPolicy: Never

          ports:
            - containerPort: 8081              
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
