apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifas-service
  namespace: karting
  labels:
    app: tarifas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarifas-service
  template:
    metadata:
      labels:
        app: tarifas-service
    spec:
      containers:
        - name: tarifas-service
          image: tarifas-service:latest
          imagePullPolicy: Never
          env:
            - name: SERVER_PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
