---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: karting
type: Opaque
stringData:
  # Root password
  mysql-root-password: rootpass
  # Usuario de aplicación
  mysql-user: appuser
  mysql-password: password

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: karting
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS reservasdb;
    CREATE DATABASE IF NOT EXISTS tarifasdb;
    CREATE DATABASE IF NOT EXISTS descuentosfrecuentesdb;
    CREATE DATABASE IF NOT EXISTS descuentospersonasdb;
    CREATE DATABASE IF NOT EXISTS tarifasespecialesdb;
    CREATE DATABASE IF NOT EXISTS reportesdb;
    -- Crea el usuario y otorga privilegios
    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'password';
    GRANT ALL PRIVILEGES ON reservasdb.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON tarifasdb.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON descuentosfrecuentesdb.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON descuentospersonasdb.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON tarifasespecialesdb.* TO 'appuser'@'%';
    GRANT ALL PRIVILEGES ON reportesdb.* TO 'appuser'@'%';
    FLUSH PRIVILEGES;

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: karting
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: reservasdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: mysql-password
        volumeMounts:
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
      volumes:
      - name: init-script
        configMap:
          name: mysql-initdb

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: karting
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
