apiVersion: v1
kind: Service
metadata:
  name: descuentos-personas-service
  namespace: karting
spec:
  type: ClusterIP
  selector:
    app: descuentos-personas-service
  ports:
    - name: http
      port: 8080        # puerto dentro del cluster
      targetPort: 8080  # debe coincidir con el containerPort
