apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: karting
spec:
  type: ClusterIP
  selector:
    app: eureka-service
  ports:
    - name: http
      port: 8761
      targetPort: 8761
