apiVersion: v1
kind: Service
metadata:
  name: reportes-service
  namespace: karting
spec:
  type: ClusterIP
  selector:
    app: reportes-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
