apiVersion: v1
kind: Service
metadata:
  name: config-service
  namespace: karting
spec:
  type: ClusterIP
  selector:
    app: config-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
