server:
  port: 8081

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ignacioa2234/ProyectoTingesoMs
          username: Ignacioa2234
          password: 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
          default-label: main
          search-paths: config-data

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
