server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Ignacioa2234/ProyectoTingesoMs
          search-paths: config-data
  application:
    name: config-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
