server:
  port: 8081

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ignacioa2234/ProyectoTingesoMs
          default-label: main
          search-paths: config-data

