spring:
  config:
    import: "configserver:http://localhost:8081"

  application:
    name: reportes-service

  cloud:
    config:
      uri: http://localhost:8081
      label: main

    netflix:
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka
  datasource:
    url: jdbc:mysql://localhost:3306/reportesdb
    username: root
    password: Ignacito1.
  jpa:
    hibernate:
          ddl-auto: update

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
