spring:
  config:
    import: optional:configserver:http://localhost:8081

  application:
    name: reportes-service

  datasource:
    url: jdbc:mysql://localhost:3306/reportesdb
    username: root
    password: Ignacito1.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info
